<a href="https://colab.research.google.com/github/rk-14311/New_repositiory/blob/main/Untitled8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
import pandas as pd

In [4]:
file_path='/content/drive/MyDrive/Cleaned_EVEN.xlsx'
df=pd.read_excel(file_path)

In [5]:
df.describe()

,booking_date,number_of_travelers,total_cost,start_date,end_date,trip_duration
count,5200,5200.000000,4937.000000,5200,5200,5200.000000
mean,2023-08-21 12:47:21.230769152,3.254808,52386.533753,2024-02-18 19:28:53.538461440,2025-02-16 19:05:37.846153984,363.983846
min,2022-08-20 00:00:00,1.000000,5010.980000,2023-08-20 00:00:00,2024-08-20 00:00:00,9.000000
25%,2023-02-20 18:00:00,2.000000,27931.950000,2023-11-19 00:00:00,2024-11-18 00:00:00,257.000000
50%,2023-08-23 00:00:00,2.000000,53023.540000,2024-02-18 00:00:00,2025-02-18 00:00:00,363.000000
75%,2024-02-21 00:00:00,3.000000,76636.490000,2024-05-19 00:00:00,2025-05-18 00:00:00,469.000000
max,2024-08-19 00:00:00,10.000000,99979.710000,2024-08-19 00:00:00,2025-08-19 00:00:00,728.000000
std,NaN,2.491585,27720.304328,NaN,NaN,149.247882

In [6]:
df['luxury'] = 53732.46515771526

In [7]:
df['premium']= 51603.118567980695

In [8]:
df['standard']=52146.55261007536

In [9]:
df.describe()

,booking_date,number_of_travelers,total_cost,start_date,end_date,trip_duration,luxury,premium,standard
count,5200,5200.000000,4937.000000,5200,5200,5200.000000,5.250000e+03,5.250000e+03,5.250000e+03
mean,2023-08-21 12:47:21.230769152,3.254808,52386.533753,2024-02-18 19:28:53.538461440,2025-02-16 19:05:37.846153984,363.983846,5.373247e+04,5.160312e+04,5.214655e+04
min,2022-08-20 00:00:00,1.000000,5010.980000,2023-08-20 00:00:00,2024-08-20 00:00:00,9.000000,5.373247e+04,5.160312e+04,5.214655e+04
25%,2023-02-20 18:00:00,2.000000,27931.950000,2023-11-19 00:00:00,2024-11-18 00:00:00,257.000000,5.373247e+04,5.160312e+04,5.214655e+04
50%,2023-08-23 00:00:00,2.000000,53023.540000,2024-02-18 00:00:00,2025-02-18 00:00:00,363.000000,5.373247e+04,5.160312e+04,5.214655e+04
75%,2024-02-21 00:00:00,3.000000,76636.490000,2024-05-19 00:00:00,2025-05-18 00:00:00,469.000000,5.373247e+04,5.160312e+04,5.214655e+04
max,2024-08-19 00:00:00,10.000000,99979.710000,2024-08-19 00:00:00,2025-08-19 00:00:00,728.000000,5.373247e+04,5.160312e+04,5.214655e+04
std,NaN,2.491585,27720.304328,NaN,NaN,149.247882,4.220457e-10,5.195529e-09,3.543729e-09

In [10]:
df['Unique Destinations Count']=858